# Generated by Django 5.0 on 2023-12-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
